name: Deploy To Netlify
 
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Deployment
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: .   # Your site root (or "dist" if you have a build step)
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}